/*
 * Copyright(c) 2021 isaki
 * Licensed under the GPL v3 license. See https://github.com/BardMusicPlayer/BardMusicPlayer/blob/develop/LICENSE for full license information.
 */

using System;

namespace BardMusicPlayer.Jamboree
{
    sealed internal class BmpSerializedServerSocket : ISerializedServerSocket
    {
        private readonly IServerSocket listener;
        private readonly ISerializedSocketAcceptor accecptor;
        private bool disposedValue;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="listener"></param>
        /// <param name="acceptor"></param>
        internal BmpSerializedServerSocket(IServerSocket listener, ISerializedSocketAcceptor acceptor)
        {
            this.listener = listener ?? throw new ArgumentNullException();
            this.accecptor = acceptor ?? throw new ArgumentNullException();
            this.disposedValue = false;
        }

        /// <inheritdoc/>
        public ISerializedSocket Accept()
        {
            ISerializedSocket ret;
            
            for (;;)
            {
                ISocket accepted = this.listener.Accept();
                ret = this.accecptor.Accept(accepted);
                if (ret != null)
                {
                    break;
                }

                accepted.Close();
            }

            return ret;
        }

        /// <inheritdoc/>
        public void Close()
        {
            this.listener.Close();
        }

        /// <inheritdoc/>
        public bool IsBound()
        {
            return this.listener.IsBound();
        }

        /// <inheritdoc/>
        public bool IsClosed()
        {
            return this.listener.IsClosed();
        }

        /// <inheritdoc/>
        public void Dispose()
        {
            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Dispose pattern generated by VS2019.
        /// </summary>
        /// <param name="disposing"></param>
        private void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    try
                    {
                        this.Close();
                    }
                    catch (Exception)
                    {
                        // Nothing to do here.
                    }
                    finally
                    {
                        this.listener.Dispose();
                    }
                }

                disposedValue = true;
            }
        }
    }
}
