//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharlayan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sharlayan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;1&quot;: {
        ///    &quot;ActionCategory&quot;: 8,
        ///    &quot;ActionCombo&quot;: 0,
        ///    &quot;ActionData&quot;: 0,
        ///    &quot;ActionProcStatus&quot;: 0,
        ///    &quot;ActionTimelineHit&quot;: 1875,
        ///    &quot;ActionTimelineUse&quot;: 85,
        ///    &quot;CanTargetDead&quot;: 1,
        ///    &quot;CanTargetFriendly&quot;: 0,
        ///    &quot;CanTargetHostile&quot;: 1,
        ///    &quot;CanTargetParty&quot;: 0,
        ///    &quot;CanTargetSelf&quot;: 0,
        ///    &quot;CastRange&quot;: 3,
        ///    &quot;CastTime&quot;: 0.0,
        ///    &quot;ClassJob&quot;: 0,
        ///    &quot;ClassJobCategory&quot;: 1,
        ///    &quot;Cost&quot;: 0,
        ///    &quot;CostCP&quot;: 0,
        ///    &quot;Duration&quot;: 0.0,
        ///    &quot;EffectRange&quot;: 0,
        ///    &quot;HasNoInitialResult&quot;: false,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;ASMSignature&quot;: true,
        ///        &quot;Key&quot;: &quot;WORLD&quot;,
        ///        &quot;PointerPath&quot;: [
        ///            -13,
        ///            0,
        ///            -112,
        ///            0
        ///        ],
        ///        &quot;Value&quot;: &quot;40534883EC40488B05********488BD98B401485C00F&quot;
        ///    },
        ///    {
        ///        &quot;ASMSignature&quot;: true,
        ///        &quot;Key&quot;: &quot;TARGET&quot;,
        ///        &quot;PointerPath&quot;: [
        ///            0,
        ///            144
        ///        ],
        ///        &quot;Value&quot;: &quot;41bc000000e041bd01000000493bc47555488d0d&quot;
        ///    },
        ///    {
        ///        &quot;ASMSignature&quot;: true,
        ///        &quot;Key&quot;: &quot;CHATLOG&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string signatures {
            get {
                return ResourceManager.GetString("signatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;1&quot;: {
        ///    &quot;CompanyAction&quot;: false,
        ///    &quot;Name&quot;: {
        ///      &quot;Chinese&quot;: &quot;???&quot;,
        ///      &quot;English&quot;: &quot;Petrification&quot;,
        ///      &quot;French&quot;: &quot;Pétrification&quot;,
        ///      &quot;German&quot;: &quot;Stein&quot;,
        ///      &quot;Japanese&quot;: &quot;石化&quot;,
        ///      &quot;Korean&quot;: &quot;???&quot;
        ///    }
        ///  },
        ///  &quot;2&quot;: {
        ///    &quot;CompanyAction&quot;: false,
        ///    &quot;Name&quot;: {
        ///      &quot;Chinese&quot;: &quot;???&quot;,
        ///      &quot;English&quot;: &quot;Stun&quot;,
        ///      &quot;French&quot;: &quot;Étourdissement&quot;,
        ///      &quot;German&quot;: &quot;Betäubung&quot;,
        ///      &quot;Japanese&quot;: &quot;スタン&quot;,
        ///      &quot;Korean&quot;: &quot;???&quot;
        ///    }
        ///  },
        ///  &quot;3&quot;: {
        ///    &quot;CompanyAction&quot;: false,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string statuses {
            get {
                return ResourceManager.GetString("statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;ActorItem&quot;: {
        ///        &quot;SourceSize&quot;: 9200,
        ///        &quot;DefaultBaseOffset&quot;: 0,
        ///        &quot;DefaultStatOffset&quot;: 0,
        ///        &quot;DefaultStatusEffectOffset&quot;: 6152,
        ///        &quot;Name&quot;: 48,
        ///        &quot;ID&quot;: 116,
        ///        &quot;NPCID1&quot;: 120,
        ///        &quot;NPCID2&quot;: 128,
        ///        &quot;OwnerID&quot;: 132,
        ///        &quot;Type&quot;: 140,
        ///        &quot;GatheringStatus&quot;: 145,
        ///        &quot;Distance&quot;: 146,
        ///        &quot;TargetFlags&quot;: 148,
        ///        &quot;GatheringInvisible&quot;: 148,
        ///        &quot;X&quot;: 160,
        ///        &quot;Z&quot;: 164,
        ///        &quot;Y&quot;: 168,
        ///        &quot;Heading&quot;: 176,
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string structures {
            get {
                return ResourceManager.GetString("structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;0&quot;: {
        ///    &quot;Index&quot;: 0,
        ///    &quot;IsDungeonInstance&quot;: false,
        ///    &quot;Name&quot;: {
        ///      &quot;Chinese&quot;: &quot;???&quot;,
        ///      &quot;English&quot;: &quot;???&quot;,
        ///      &quot;French&quot;: &quot;???&quot;,
        ///      &quot;German&quot;: &quot;???&quot;,
        ///      &quot;Japanese&quot;: &quot;？？？？&quot;,
        ///      &quot;Korean&quot;: &quot;???&quot;
        ///    }
        ///  },
        ///  &quot;1&quot;: {
        ///    &quot;Index&quot;: 0,
        ///    &quot;IsDungeonInstance&quot;: false,
        ///    &quot;Name&quot;: {
        ///      &quot;Chinese&quot;: &quot;Eorzea&quot;,
        ///      &quot;English&quot;: &quot;Eorzea&quot;,
        ///      &quot;French&quot;: &quot;Éorzéa&quot;,
        ///      &quot;German&quot;: &quot;Eorzea&quot;,
        ///      &quot;Japanese&quot;: &quot;エオルゼア&quot;,
        ///      &quot;Korean&quot;: &quot;Eorzea&quot;
        ///    }
        ///  },
        ///  &quot;128&quot;: {
        ///    &quot;Inde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string zones {
            get {
                return ResourceManager.GetString("zones", resourceCulture);
            }
        }
    }
}
