name: Test PR against develop

on:
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: windows-latest

    env:
      Solution_Name: BardMusicPlayer

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: 'main'

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build with dotnet
      run: dotnet build --configuration Debug

    # Unit tests go here. Some day we may actually have unit test in BMP. ¯\_(ツ)_/¯

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BardMusicPlayer
        path: BardMusicPlayer\bin\Debug\net48\*.exe
        if-no-files-found: error
        retention-days: 1
