name: Test PR against develop

on:
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build with dotnet
      run: dotnet build --configuration Debug

    # Unit tests go here. Some day we may actually have unit test in BMP. ¯\_(ツ)_/¯